version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/node/Dockerfile"
    tty: true
    command: "npx ts-node app.ts"
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app"
